package com.dbtw.models.standard;

public class Address {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column address.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column address.street1
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String street1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column address.street2
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String street2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column address.street3
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String street3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column address.city
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String city;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column address.zip
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer zip;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column address.plus4
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer plus4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column address.States_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer statesId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column address.street1
     *
     * @return the value of address.street1
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getStreet1() {
        return street1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column address.street1
     *
     * @param street1 the value for address.street1
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setStreet1(String street1) {
        this.street1 = street1 == null ? null : street1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column address.street2
     *
     * @return the value of address.street2
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getStreet2() {
        return street2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column address.street2
     *
     * @param street2 the value for address.street2
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setStreet2(String street2) {
        this.street2 = street2 == null ? null : street2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column address.street3
     *
     * @return the value of address.street3
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getStreet3() {
        return street3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column address.street3
     *
     * @param street3 the value for address.street3
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setStreet3(String street3) {
        this.street3 = street3 == null ? null : street3.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column address.zip
     *
     * @return the value of address.zip
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getZip() {
        return zip;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column address.zip
     *
     * @param zip the value for address.zip
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setZip(Integer zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column address.plus4
     *
     * @return the value of address.plus4
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getPlus4() {
        return plus4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column address.plus4
     *
     * @param plus4 the value for address.plus4
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setPlus4(Integer plus4) {
        this.plus4 = plus4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column address.States_id
     *
     * @return the value of address.States_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getStatesId() {
        return statesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column address.States_id
     *
     * @param statesId the value for address.States_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setStatesId(Integer statesId) {
        this.statesId = statesId;
    }
}