package com.dbtw.models.standard;

public class Addressusetypes {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column addressusetypes.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column addressusetypes.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column addressusetypes.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String description;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column addressusetypes.id
     *
     * @return the value of addressusetypes.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column addressusetypes.id
     *
     * @param id the value for addressusetypes.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column addressusetypes.name
     *
     * @return the value of addressusetypes.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column addressusetypes.name
     *
     * @param name the value for addressusetypes.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column addressusetypes.description
     *
     * @return the value of addressusetypes.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column addressusetypes.description
     *
     * @param description the value for addressusetypes.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}