package com.dbtw.models.standard;

import java.util.Date;

public class Allowableexpenses {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column allowableexpenses.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column allowableexpenses.effective_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date effectiveFrom;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column allowableexpenses.effective_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date effectiveTo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column allowableexpenses.amount
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Double amount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column allowableexpenses.ExpenseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer expensetypesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column allowableexpenses.TaskOrders_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer taskordersId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column allowableexpenses.id
     *
     * @return the value of allowableexpenses.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column allowableexpenses.id
     *
     * @param id the value for allowableexpenses.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column allowableexpenses.effective_from
     *
     * @return the value of allowableexpenses.effective_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getEffectiveFrom() {
        return effectiveFrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column allowableexpenses.effective_from
     *
     * @param effectiveFrom the value for allowableexpenses.effective_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column allowableexpenses.effective_to
     *
     * @return the value of allowableexpenses.effective_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getEffectiveTo() {
        return effectiveTo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column allowableexpenses.effective_to
     *
     * @param effectiveTo the value for allowableexpenses.effective_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column allowableexpenses.amount
     *
     * @return the value of allowableexpenses.amount
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column allowableexpenses.amount
     *
     * @param amount the value for allowableexpenses.amount
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column allowableexpenses.ExpenseTypes_id
     *
     * @return the value of allowableexpenses.ExpenseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getExpensetypesId() {
        return expensetypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column allowableexpenses.ExpenseTypes_id
     *
     * @param expensetypesId the value for allowableexpenses.ExpenseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setExpensetypesId(Integer expensetypesId) {
        this.expensetypesId = expensetypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column allowableexpenses.TaskOrders_id
     *
     * @return the value of allowableexpenses.TaskOrders_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getTaskordersId() {
        return taskordersId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column allowableexpenses.TaskOrders_id
     *
     * @param taskordersId the value for allowableexpenses.TaskOrders_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setTaskordersId(Integer taskordersId) {
        this.taskordersId = taskordersId;
    }
}