package com.dbtw.models.standard;

import java.util.Date;

public class Assignments {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column assignments.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column assignments.task_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer taskId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column assignments.employee_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer employeeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column assignments.effective_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date effectiveFrom;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column assignments.effective_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date effectiveTo;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column assignments.id
     *
     * @return the value of assignments.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column assignments.id
     *
     * @param id the value for assignments.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column assignments.task_id
     *
     * @return the value of assignments.task_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column assignments.task_id
     *
     * @param taskId the value for assignments.task_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column assignments.employee_id
     *
     * @return the value of assignments.employee_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column assignments.employee_id
     *
     * @param employeeId the value for assignments.employee_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column assignments.effective_from
     *
     * @return the value of assignments.effective_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getEffectiveFrom() {
        return effectiveFrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column assignments.effective_from
     *
     * @param effectiveFrom the value for assignments.effective_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column assignments.effective_to
     *
     * @return the value of assignments.effective_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getEffectiveTo() {
        return effectiveTo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column assignments.effective_to
     *
     * @param effectiveTo the value for assignments.effective_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }
}