package com.dbtw.models.standard;

import java.util.Date;

public class Autorentals {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autorentals.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autorentals.vendor_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer vendorId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autorentals.start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date start;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autorentals.stop
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date stop;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autorentals.rate
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Double rate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autorentals.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Double actual;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autorentals.ExpenseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer expensetypesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autorentals.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer employeesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autorentals.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer allowableexpensesId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autorentals.id
     *
     * @return the value of autorentals.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autorentals.id
     *
     * @param id the value for autorentals.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autorentals.vendor_id
     *
     * @return the value of autorentals.vendor_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autorentals.vendor_id
     *
     * @param vendorId the value for autorentals.vendor_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autorentals.start
     *
     * @return the value of autorentals.start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autorentals.start
     *
     * @param start the value for autorentals.start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autorentals.stop
     *
     * @return the value of autorentals.stop
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getStop() {
        return stop;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autorentals.stop
     *
     * @param stop the value for autorentals.stop
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setStop(Date stop) {
        this.stop = stop;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autorentals.rate
     *
     * @return the value of autorentals.rate
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autorentals.rate
     *
     * @param rate the value for autorentals.rate
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autorentals.actual
     *
     * @return the value of autorentals.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Double getActual() {
        return actual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autorentals.actual
     *
     * @param actual the value for autorentals.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setActual(Double actual) {
        this.actual = actual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autorentals.ExpenseTypes_id
     *
     * @return the value of autorentals.ExpenseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getExpensetypesId() {
        return expensetypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autorentals.ExpenseTypes_id
     *
     * @param expensetypesId the value for autorentals.ExpenseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setExpensetypesId(Integer expensetypesId) {
        this.expensetypesId = expensetypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autorentals.Employees_id
     *
     * @return the value of autorentals.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getEmployeesId() {
        return employeesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autorentals.Employees_id
     *
     * @param employeesId the value for autorentals.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEmployeesId(Integer employeesId) {
        this.employeesId = employeesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autorentals.AllowableExpenses_id
     *
     * @return the value of autorentals.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getAllowableexpensesId() {
        return allowableexpensesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autorentals.AllowableExpenses_id
     *
     * @param allowableexpensesId the value for autorentals.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setAllowableexpensesId(Integer allowableexpensesId) {
        this.allowableexpensesId = allowableexpensesId;
    }
}