package com.dbtw.models.standard;

import java.util.Date;

public class Commercialair {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column commercialair.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column commercialair.departed
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date departed;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column commercialair.returned
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date returned;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column commercialair.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Double actual;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column commercialair.carrier_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer carrierId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column commercialair.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer employeesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column commercialair.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer allowableexpensesId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column commercialair.id
     *
     * @return the value of commercialair.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column commercialair.id
     *
     * @param id the value for commercialair.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column commercialair.departed
     *
     * @return the value of commercialair.departed
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getDeparted() {
        return departed;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column commercialair.departed
     *
     * @param departed the value for commercialair.departed
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setDeparted(Date departed) {
        this.departed = departed;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column commercialair.returned
     *
     * @return the value of commercialair.returned
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getReturned() {
        return returned;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column commercialair.returned
     *
     * @param returned the value for commercialair.returned
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setReturned(Date returned) {
        this.returned = returned;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column commercialair.actual
     *
     * @return the value of commercialair.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Double getActual() {
        return actual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column commercialair.actual
     *
     * @param actual the value for commercialair.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setActual(Double actual) {
        this.actual = actual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column commercialair.carrier_id
     *
     * @return the value of commercialair.carrier_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getCarrierId() {
        return carrierId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column commercialair.carrier_id
     *
     * @param carrierId the value for commercialair.carrier_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setCarrierId(Integer carrierId) {
        this.carrierId = carrierId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column commercialair.Employees_id
     *
     * @return the value of commercialair.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getEmployeesId() {
        return employeesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column commercialair.Employees_id
     *
     * @param employeesId the value for commercialair.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEmployeesId(Integer employeesId) {
        this.employeesId = employeesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column commercialair.AllowableExpenses_id
     *
     * @return the value of commercialair.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getAllowableexpensesId() {
        return allowableexpensesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column commercialair.AllowableExpenses_id
     *
     * @param allowableexpensesId the value for commercialair.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setAllowableexpensesId(Integer allowableexpensesId) {
        this.allowableexpensesId = allowableexpensesId;
    }
}