package com.dbtw.models.standard;

import java.util.Date;

public class Companyaddressuse {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column companyaddressuse.effective_start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date effectiveStart;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column companyaddressuse.effective_end
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date effectiveEnd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column companyaddressuse.Address_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer addressId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column companyaddressuse.AddressUseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer addressusetypesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column companyaddressuse.Companies_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer companiesId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column companyaddressuse.effective_start
     *
     * @return the value of companyaddressuse.effective_start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getEffectiveStart() {
        return effectiveStart;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column companyaddressuse.effective_start
     *
     * @param effectiveStart the value for companyaddressuse.effective_start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEffectiveStart(Date effectiveStart) {
        this.effectiveStart = effectiveStart;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column companyaddressuse.effective_end
     *
     * @return the value of companyaddressuse.effective_end
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getEffectiveEnd() {
        return effectiveEnd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column companyaddressuse.effective_end
     *
     * @param effectiveEnd the value for companyaddressuse.effective_end
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEffectiveEnd(Date effectiveEnd) {
        this.effectiveEnd = effectiveEnd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column companyaddressuse.Address_id
     *
     * @return the value of companyaddressuse.Address_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column companyaddressuse.Address_id
     *
     * @param addressId the value for companyaddressuse.Address_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column companyaddressuse.AddressUseTypes_id
     *
     * @return the value of companyaddressuse.AddressUseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getAddressusetypesId() {
        return addressusetypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column companyaddressuse.AddressUseTypes_id
     *
     * @param addressusetypesId the value for companyaddressuse.AddressUseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setAddressusetypesId(Integer addressusetypesId) {
        this.addressusetypesId = addressusetypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column companyaddressuse.Companies_id
     *
     * @return the value of companyaddressuse.Companies_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getCompaniesId() {
        return companiesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column companyaddressuse.Companies_id
     *
     * @param companiesId the value for companyaddressuse.Companies_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setCompaniesId(Integer companiesId) {
        this.companiesId = companiesId;
    }
}