package com.dbtw.models.standard;

import java.util.Date;

public class Contracts {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column contracts.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column contracts.title
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String title;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column contracts.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column contracts.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column contracts.start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date start;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column contracts.stop
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date stop;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contracts.id
     *
     * @return the value of contracts.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contracts.id
     *
     * @param id the value for contracts.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contracts.title
     *
     * @return the value of contracts.title
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contracts.title
     *
     * @param title the value for contracts.title
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contracts.name
     *
     * @return the value of contracts.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contracts.name
     *
     * @param name the value for contracts.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contracts.description
     *
     * @return the value of contracts.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contracts.description
     *
     * @param description the value for contracts.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contracts.start
     *
     * @return the value of contracts.start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contracts.start
     *
     * @param start the value for contracts.start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contracts.stop
     *
     * @return the value of contracts.stop
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getStop() {
        return stop;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contracts.stop
     *
     * @param stop the value for contracts.stop
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setStop(Date stop) {
        this.stop = stop;
    }
}