package com.dbtw.models.standard;

import java.util.Date;

public class Employees {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column employees.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column employees.person_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer personId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column employees.company_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer companyId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column employees.effective_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date effectiveFrom;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column employees.effective_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date effectiveTo;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column employees.id
     *
     * @return the value of employees.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column employees.id
     *
     * @param id the value for employees.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column employees.person_id
     *
     * @return the value of employees.person_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column employees.person_id
     *
     * @param personId the value for employees.person_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column employees.company_id
     *
     * @return the value of employees.company_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column employees.company_id
     *
     * @param companyId the value for employees.company_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column employees.effective_from
     *
     * @return the value of employees.effective_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getEffectiveFrom() {
        return effectiveFrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column employees.effective_from
     *
     * @param effectiveFrom the value for employees.effective_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column employees.effective_to
     *
     * @return the value of employees.effective_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getEffectiveTo() {
        return effectiveTo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column employees.effective_to
     *
     * @param effectiveTo the value for employees.effective_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }
}