package com.dbtw.models.standard;

import java.util.Date;

public class Gas {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gas.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gas.gallons
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Double gallons;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gas.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Double actual;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gas.pumped
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date pumped;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gas.autorental_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer autorentalId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gas.AutoRentals_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer autorentalsId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gas.id
     *
     * @return the value of gas.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gas.id
     *
     * @param id the value for gas.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gas.gallons
     *
     * @return the value of gas.gallons
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Double getGallons() {
        return gallons;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gas.gallons
     *
     * @param gallons the value for gas.gallons
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setGallons(Double gallons) {
        this.gallons = gallons;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gas.actual
     *
     * @return the value of gas.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Double getActual() {
        return actual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gas.actual
     *
     * @param actual the value for gas.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setActual(Double actual) {
        this.actual = actual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gas.pumped
     *
     * @return the value of gas.pumped
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getPumped() {
        return pumped;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gas.pumped
     *
     * @param pumped the value for gas.pumped
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setPumped(Date pumped) {
        this.pumped = pumped;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gas.autorental_id
     *
     * @return the value of gas.autorental_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getAutorentalId() {
        return autorentalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gas.autorental_id
     *
     * @param autorentalId the value for gas.autorental_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setAutorentalId(Integer autorentalId) {
        this.autorentalId = autorentalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gas.AutoRentals_id
     *
     * @return the value of gas.AutoRentals_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getAutorentalsId() {
        return autorentalsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gas.AutoRentals_id
     *
     * @param autorentalsId the value for gas.AutoRentals_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setAutorentalsId(Integer autorentalsId) {
        this.autorentalsId = autorentalsId;
    }
}