package com.dbtw.models.standard;

import java.util.Date;

public class Hotels {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column hotels.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column hotels.check_in
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date checkIn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column hotels.check_out
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date checkOut;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column hotels.rate
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Double rate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column hotels.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Double actual;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column hotels.Companies_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer companiesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column hotels.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer allowableexpensesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column hotels.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer employeesId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column hotels.id
     *
     * @return the value of hotels.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column hotels.id
     *
     * @param id the value for hotels.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column hotels.check_in
     *
     * @return the value of hotels.check_in
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getCheckIn() {
        return checkIn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column hotels.check_in
     *
     * @param checkIn the value for hotels.check_in
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setCheckIn(Date checkIn) {
        this.checkIn = checkIn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column hotels.check_out
     *
     * @return the value of hotels.check_out
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getCheckOut() {
        return checkOut;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column hotels.check_out
     *
     * @param checkOut the value for hotels.check_out
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setCheckOut(Date checkOut) {
        this.checkOut = checkOut;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column hotels.rate
     *
     * @return the value of hotels.rate
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column hotels.rate
     *
     * @param rate the value for hotels.rate
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column hotels.actual
     *
     * @return the value of hotels.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Double getActual() {
        return actual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column hotels.actual
     *
     * @param actual the value for hotels.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setActual(Double actual) {
        this.actual = actual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column hotels.Companies_id
     *
     * @return the value of hotels.Companies_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getCompaniesId() {
        return companiesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column hotels.Companies_id
     *
     * @param companiesId the value for hotels.Companies_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setCompaniesId(Integer companiesId) {
        this.companiesId = companiesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column hotels.AllowableExpenses_id
     *
     * @return the value of hotels.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getAllowableexpensesId() {
        return allowableexpensesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column hotels.AllowableExpenses_id
     *
     * @param allowableexpensesId the value for hotels.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setAllowableexpensesId(Integer allowableexpensesId) {
        this.allowableexpensesId = allowableexpensesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column hotels.Employees_id
     *
     * @return the value of hotels.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getEmployeesId() {
        return employeesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column hotels.Employees_id
     *
     * @param employeesId the value for hotels.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEmployeesId(Integer employeesId) {
        this.employeesId = employeesId;
    }
}