package com.dbtw.models.standard;

import java.util.Date;

public class Meals {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column meals.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column meals.eaten
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date eaten;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column meals.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Double actual;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column meals.MealTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer mealtypesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column meals.ExpenseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer expensetypesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column meals.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer employeesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column meals.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer allowableexpensesId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column meals.id
     *
     * @return the value of meals.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column meals.id
     *
     * @param id the value for meals.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column meals.eaten
     *
     * @return the value of meals.eaten
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getEaten() {
        return eaten;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column meals.eaten
     *
     * @param eaten the value for meals.eaten
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEaten(Date eaten) {
        this.eaten = eaten;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column meals.actual
     *
     * @return the value of meals.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Double getActual() {
        return actual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column meals.actual
     *
     * @param actual the value for meals.actual
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setActual(Double actual) {
        this.actual = actual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column meals.MealTypes_id
     *
     * @return the value of meals.MealTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getMealtypesId() {
        return mealtypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column meals.MealTypes_id
     *
     * @param mealtypesId the value for meals.MealTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setMealtypesId(Integer mealtypesId) {
        this.mealtypesId = mealtypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column meals.ExpenseTypes_id
     *
     * @return the value of meals.ExpenseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getExpensetypesId() {
        return expensetypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column meals.ExpenseTypes_id
     *
     * @param expensetypesId the value for meals.ExpenseTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setExpensetypesId(Integer expensetypesId) {
        this.expensetypesId = expensetypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column meals.Employees_id
     *
     * @return the value of meals.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getEmployeesId() {
        return employeesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column meals.Employees_id
     *
     * @param employeesId the value for meals.Employees_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEmployeesId(Integer employeesId) {
        this.employeesId = employeesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column meals.AllowableExpenses_id
     *
     * @return the value of meals.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getAllowableexpensesId() {
        return allowableexpensesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column meals.AllowableExpenses_id
     *
     * @param allowableexpensesId the value for meals.AllowableExpenses_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setAllowableexpensesId(Integer allowableexpensesId) {
        this.allowableexpensesId = allowableexpensesId;
    }
}