package com.dbtw.models.standard;

import java.util.Date;

public class Persons {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persons.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persons.first_name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String firstName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persons.middle_name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String middleName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persons.last_name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String lastName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persons.dob
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date dob;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persons.ssn
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer ssn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persons.id
     *
     * @return the value of persons.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persons.id
     *
     * @param id the value for persons.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persons.first_name
     *
     * @return the value of persons.first_name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persons.first_name
     *
     * @param firstName the value for persons.first_name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persons.middle_name
     *
     * @return the value of persons.middle_name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persons.middle_name
     *
     * @param middleName the value for persons.middle_name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setMiddleName(String middleName) {
        this.middleName = middleName == null ? null : middleName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persons.last_name
     *
     * @return the value of persons.last_name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persons.last_name
     *
     * @param lastName the value for persons.last_name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persons.dob
     *
     * @return the value of persons.dob
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getDob() {
        return dob;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persons.dob
     *
     * @param dob the value for persons.dob
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setDob(Date dob) {
        this.dob = dob;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persons.ssn
     *
     * @return the value of persons.ssn
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getSsn() {
        return ssn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persons.ssn
     *
     * @param ssn the value for persons.ssn
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setSsn(Integer ssn) {
        this.ssn = ssn;
    }
}