package com.dbtw.models.standard;

public class Servicefees {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column servicefees.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column servicefees.fee
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Double fee;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column servicefees.ServiceFeeTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer servicefeetypesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column servicefees.CommercialAir_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer commercialairId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column servicefees.id
     *
     * @return the value of servicefees.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column servicefees.id
     *
     * @param id the value for servicefees.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column servicefees.fee
     *
     * @return the value of servicefees.fee
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Double getFee() {
        return fee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column servicefees.fee
     *
     * @param fee the value for servicefees.fee
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setFee(Double fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column servicefees.ServiceFeeTypes_id
     *
     * @return the value of servicefees.ServiceFeeTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getServicefeetypesId() {
        return servicefeetypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column servicefees.ServiceFeeTypes_id
     *
     * @param servicefeetypesId the value for servicefees.ServiceFeeTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setServicefeetypesId(Integer servicefeetypesId) {
        this.servicefeetypesId = servicefeetypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column servicefees.CommercialAir_id
     *
     * @return the value of servicefees.CommercialAir_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getCommercialairId() {
        return commercialairId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column servicefees.CommercialAir_id
     *
     * @param commercialairId the value for servicefees.CommercialAir_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setCommercialairId(Integer commercialairId) {
        this.commercialairId = commercialairId;
    }
}