package com.dbtw.models.standard;

public class States {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column states.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column states.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column states.abbrev
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String abbrev;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column states.id
     *
     * @return the value of states.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column states.id
     *
     * @param id the value for states.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column states.name
     *
     * @return the value of states.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column states.name
     *
     * @param name the value for states.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column states.abbrev
     *
     * @return the value of states.abbrev
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getAbbrev() {
        return abbrev;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column states.abbrev
     *
     * @param abbrev the value for states.abbrev
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setAbbrev(String abbrev) {
        this.abbrev = abbrev == null ? null : abbrev.trim();
    }
}