package com.dbtw.models.standard;

import java.util.Date;

public class Tasktypes {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasktypes.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasktypes.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasktypes.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasktypes.valid_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date validFrom;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasktypes.valid_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date validTo;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasktypes.id
     *
     * @return the value of tasktypes.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasktypes.id
     *
     * @param id the value for tasktypes.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasktypes.name
     *
     * @return the value of tasktypes.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasktypes.name
     *
     * @param name the value for tasktypes.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasktypes.description
     *
     * @return the value of tasktypes.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasktypes.description
     *
     * @param description the value for tasktypes.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasktypes.valid_from
     *
     * @return the value of tasktypes.valid_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getValidFrom() {
        return validFrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasktypes.valid_from
     *
     * @param validFrom the value for tasktypes.valid_from
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasktypes.valid_to
     *
     * @return the value of tasktypes.valid_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getValidTo() {
        return validTo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasktypes.valid_to
     *
     * @param validTo the value for tasktypes.valid_to
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setValidTo(Date validTo) {
        this.validTo = validTo;
    }
}