package com.dbtw.models.standard;

import java.util.Date;

public class Tasks {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasks.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasks.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasks.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasks.start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date start;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasks.stop
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date stop;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasks.TaskOrders_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer taskordersId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasks.TaskTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer tasktypesId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasks.id
     *
     * @return the value of tasks.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasks.id
     *
     * @param id the value for tasks.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasks.name
     *
     * @return the value of tasks.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasks.name
     *
     * @param name the value for tasks.name
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasks.description
     *
     * @return the value of tasks.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasks.description
     *
     * @param description the value for tasks.description
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasks.start
     *
     * @return the value of tasks.start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasks.start
     *
     * @param start the value for tasks.start
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasks.stop
     *
     * @return the value of tasks.stop
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getStop() {
        return stop;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasks.stop
     *
     * @param stop the value for tasks.stop
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setStop(Date stop) {
        this.stop = stop;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasks.TaskOrders_id
     *
     * @return the value of tasks.TaskOrders_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getTaskordersId() {
        return taskordersId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasks.TaskOrders_id
     *
     * @param taskordersId the value for tasks.TaskOrders_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setTaskordersId(Integer taskordersId) {
        this.taskordersId = taskordersId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasks.TaskTypes_id
     *
     * @return the value of tasks.TaskTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getTasktypesId() {
        return tasktypesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasks.TaskTypes_id
     *
     * @param tasktypesId the value for tasks.TaskTypes_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setTasktypesId(Integer tasktypesId) {
        this.tasktypesId = tasktypesId;
    }
}