package com.dbtw.models.standard;

import java.util.Date;

public class Timeclock {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column timeclock.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column timeclock.employee_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer employeeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column timeclock.workperformed_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Integer workperformedId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column timeclock.time_in
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date timeIn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column timeclock.time_out
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    private Date timeOut;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column timeclock.id
     *
     * @return the value of timeclock.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column timeclock.id
     *
     * @param id the value for timeclock.id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column timeclock.employee_id
     *
     * @return the value of timeclock.employee_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column timeclock.employee_id
     *
     * @param employeeId the value for timeclock.employee_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column timeclock.workperformed_id
     *
     * @return the value of timeclock.workperformed_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Integer getWorkperformedId() {
        return workperformedId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column timeclock.workperformed_id
     *
     * @param workperformedId the value for timeclock.workperformed_id
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setWorkperformedId(Integer workperformedId) {
        this.workperformedId = workperformedId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column timeclock.time_in
     *
     * @return the value of timeclock.time_in
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getTimeIn() {
        return timeIn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column timeclock.time_in
     *
     * @param timeIn the value for timeclock.time_in
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setTimeIn(Date timeIn) {
        this.timeIn = timeIn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column timeclock.time_out
     *
     * @return the value of timeclock.time_out
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public Date getTimeOut() {
        return timeOut;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column timeclock.time_out
     *
     * @param timeOut the value for timeclock.time_out
     *
     * @ibatorgenerated Thu May 27 15:19:22 MDT 2010
     */
    public void setTimeOut(Date timeOut) {
        this.timeOut = timeOut;
    }
}